version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    schedule:
      interval: "daily"
      time: "12:44"
      timezone: "America/Bogota"
    directory: "/Virtual-Coach_BackEnd"
    target:
      files:
        - path: ".gitmodules"
          update:
            target: "develop"
            
  - package-ecosystem: "gitsubmodule"
    schedule:
      interval: "daily"
      time: "12:44"
      timezone: "America/Bogota"
    directory: "/Virtual-Coach_Frontend"
    target:
      files:
        - path: ".gitmodules"
          update:
            target: "develop"
