version: '3.7'

services:

  frontend:
    build:
      context: ./Virtual-Coach_FrontEnd
    volumes:
      - frontend:/app/dist

  backend:
    volumes:
      - static:/static
    build:
      context: ./Virtual-Coach_Backend/virtual_c
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend: